[package]
name = "bundle"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bundle-rs"
path = "src/main.rs"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
